type: object
required: ["homeserver", "rocket_chat_webhook_port", "bot_username", "username_prefix"]
properties:
  homeserver:
    type: object
    required: ["server_name", "url"]
    properties:
      server_name:
        type: string
      url:
        type: string
  tls:
    type: object
    required: ["key_file", "crt_file"]
    properties:
      key_file:
        type: string
      crt_file:
        type: string
  rocket_chat_webhook_port:
    type: integer
  rooms:
    type: array
    items:
      type: object
      required: ["matrix_room_id", "webhook_url"]
      properties:
        matrix_room_id:
          type: string
        webhook_url:
          type: string
  bot_username:
    type: string
  username_prefix:
    type: string
